factory-south-macos-slicerextensions_preview_nightly.cmake
factory-south-macos-slicerextensions_stable_nightly.cmake
overload-vs2015-slicerextensions_preview_nightly.cmake
overload-vs2015-slicerextensions_stable_nightly.cmake

It is required by SPHARM-PDM [1] and GROUPS [2] extensions.
See https://github.com/Kitware/SlicerSALT/issues/125
[1] https://github.com/NIRALUser/SPHARM-PDM
[2] https://github.com/NIRALUser/GROUPS/tree/master/SuperBuild

factory-south-macos/overload: Set FC env. variable to support building LAPACK

---

metroplex-slicer_preview_nightly.cmake
metroplex-slicerextensions_preview_nightly.cmake

**UPDATE: Read https://github.com/Slicer/DashboardScripts/pull/26#issuecomment-635027886**
--------------------------------
This PR updates the dashboard script for Metroplex to use Qt 5.12.8 and therefore requires 
- Metroplex be updated to Red Hat Enterprise Linux 7.4.
Qt 5.12.8 supports the below configuration ([source](https://doc-snapshots.qt.io/qt5-5.12/supported-platforms.html))
| Platform | Compiler | Notes |
|-----------|-----------|--------|
|Red Hat Enterprise Linux 7.4 (x86_64)| GCC 5.3.1 | devtoolset-4|
-------------------
Metroplex is currently running Red Hat Enterprise Linux 7.2 ([source](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Factory#metroplex.kitware)) and using Qt 5.11.2.
Qt 5.11.2 supports the below configuration …

metroplex: Update nightly builds to use Qt 5.15.0

---

overload-vs2019-slicer_preview_nightly.cmake
overload-vs2019-slicerextensions_preview_nightly.cmake
overload.bat

This updates the Windows nightly builds to use Qt 5.15.0 which is also using the v142 (VS 2019) toolkit.  I had a successful build without errors which requires the VTK backport https://github.com/Slicer/VTK/pull/26 to be merged and then I'll need the Slicer superbuild updated to use the new Slicer/VTK git hash.  My successful build was with CMake 3.17.2, Visual Studio 2019 16.5.4, Windows 10 1909.
A quote from the Qt [blog post](https://www.qt.io/blog/qt-5.15-released) about the 5.15 release
> A large amount of work has gone into bug fixes, and Qt 5.15 is the best and **most stable release we've done in the Qt 5 series.** 
There are of course more build warnings with Qt 5.15.0 as more things have been marked deprecated. This was done by Qt to make the transition to Qt 6 easier as Qt 5.15 …

overload: Update nightly builds to use Qt 5.15.0

---

metroplex-slicer_preview_nightly.cmake
metroplex-slicerextensions_preview_nightly.cmake
metroplex.sh

This PR adds generation of the build script to the dashboard for both Slicer Preview and SlicerSALT.  This includes rolling back to Qt 5.11.2

Generate script with dashboard

---

factory-south-macos-slicer_preview_nightly.cmake
factory-south-macos-slicerextensions_preview_nightly.cmake

**UPDATE: Read https://github.com/Slicer/DashboardScripts/pull/27#issuecomment-635024624**
--------------------------------
This PR updates the dashboard script for Metroplex to use Qt 5.12.8. This PR is starting out as a draft since it is unclear how the stable builds of slicer and its extensions will continue to be built when the macOS build machine updates. Some updates required as part of building Qt 5.12.8 from source (accomplished by https://github.com/jcfr/qt-easy-build/pull/55)
Some potential options:
- Factory-south-macos be updated to macOS 10.13.6 (latest macOS High Sierra version)
- Xcode 9.4.1 installed (macOS 10.13 High Sierra SDK) Apple LLVM version 9.1.0 (clang-902.0.39.2)
- Factory-south-macos be updated to macOS 10.14.6 (latest macOS Mojave version)
- Xcode 10.3 …

factory-south-macos: Update nightly builds to use Qt 5.15.0

---

overload-vs2015-cell-locator_preview_experimental.bat

This required to support using the newer generator "Visual Studio 16 2019"
See https://cmake.org/cmake/help/latest/release/3.14.html#new-features

overload: Fix cell-locator build updating CMake version from 3.12.2 to 3.14.3

---

metroplex-cell-locator_preview_experimental.cmake
metroplex-slicer_preview_nightly.cmake
metroplex-slicerextensions_preview_nightly.cmake
metroplex.sh
overload-vs2019-cell-locator_preview_experimental.cmake
overload-vs2019-slicer_preview_nightly.cmake
overload-vs2019-slicerextensions_preview_nightly.cmake

See  https://github.com/Slicer/DashboardScripts/pull/31

Update nightly builds for metroxplex and overload to use Qt 5.15.1 

---

factory-south-macos-slicer_preview_nightly.cmake
factory-south-macos-slicerextensions_preview_nightly.cmake
factory-south-macos-slicersalt_300_release_package.cmake
factory-south-macos-slicersalt_preview_nightly.cmake

Qt 5.15.1 was [released](https://www.qt.io/blog/qt-5.15.1-released) on September 10th.  The qt-easy-build project was updated with a [5.15.1](https://github.com/jcfr/qt-easy-build/tree/5.15.1) branch and Azure pipelines CI is currently running the update.
Primary motivation for updating to use Qt 5.15.1 is that this closes https://github.com/Slicer/Slicer/issues/5106 in the factory-built Slicer nightly packages.  Currently building Slicer with Qt 5.15.1 to confirm this bug fix.

Update nightly builds for factory-macos-south to use Qt 5.15.1

---

factory-south-macos-slicer_4102_release_package.sh
factory-south-macos-slicer_41120200930_release_package.cmake
factory-south-macos-slicer_41120200930_release_package.sh
factory-south-macos-slicerextensions_stable_nightly.cmake
metroplex-slicer_41120200930_release_package.cmake
metroplex-slicer_41120200930_release_package.sh
metroplex-slicerextensions_stable_nightly.cmake
metroplex.sh
overload-vs2019-slicer_41120200930_release_package.bat
overload-vs2019-slicer_41120200930_release_package.cmake
overload-vs2019-slicerextensions_stable_nightly.cmake
overload.bat

* Follow instructions from https://github.com/Slicer/DashboardScripts/blob/master/maintenance/guides/rename-and-update-release-scripts.md
* Rename scripts from overload-vs2015-* to overload-vs2019-*
* Update stable scripts compiler/os/... to match value from corresponding
preview scripts
* Update stable scripts to download  slicer version with tag v4.11.20200930
* Change Slicer_DIRECTORY_IDENTIFIER from 41120200930 to 0 to ensure
patch remains short enough.

ENH: Add snapshot release scripts for 4.11.20200930

---

factory-south-macos-slicer_41120210226_release_package.cmake
factory-south-macos-slicer_41120210226_release_package.sh
factory-south-macos-slicerextensions_stable_nightly.cmake
metroplex-slicer_41120210226_release_package.cmake
metroplex-slicer_41120210226_release_package.sh
metroplex-slicerextensions_stable_nightly.cmake
overload-vs2019-slicer_41120210226_release_package.bat
overload-vs2019-slicer_41120210226_release_package.cmake
overload-vs2019-slicerextensions_stable_nightly.cmake
overload.bat

* Follow instructions from https://github.com/Slicer/DashboardScripts/blob/master/maintenance/guides/rename-and-update-release-scripts.md
* Remove scripts for 4.11.20200930
* Associate 4.11.20210226 with directory identifier 1
* Manually update metroplex-slicer_41120210226_release_package to use
correct docker image name.
* Update overload.bat to delete "D:\D\S\S-1-E-b" instead of "D:\D\S\S-41120210226-E-b"

ENH: Add snapshot release scripts for 4.11.20210226

---

computron.sh
factory-south-macos.sh
maintenance/computron/remote-install-cmake.sh
maintenance/factory-south-macos/remote-install-cmake.sh
overload-vs2022-slicer_preview_nightly.cmake
overload-vs2022-slicerextensions_preview_nightly.cmake
overload.bat

This PR includes multiple build tools updates all together as they would likely be updated all at the same time by @sjh26 or @jcfr .
Updating the CMake version to 3.22.0 which includes a bug fix that should resolve uninstall issues of factory-built Slicer versions on Windows. See Slicer/Slicer#4933. It is being updated for both preview and stable build configurations.
Note that I've only updated Slicer preview build and preview extensions build to use VS2022 with v143 toolset. I have not modified the files for Slicer Stable. These could be changed once a new Stable is defined. I also am not changing SlicerSalt or CellLocator to use the newer Visual Studio due to them likely using older Slicer versions that won't build successfully with the latest toolset.
Visual Studio 2022 biggest change …

Update CMake and Visual Studio build tools

---

factory-south-macos-slicer_41120210226_release_package.sh
factory-south-macos-slicer_500_release_package.cmake
factory-south-macos-slicer_500_release_package.sh
factory-south-macos-slicerextensions_stable_nightly.cmake
metroplex-slicer_500_release_package.cmake
metroplex-slicer_500_release_package.sh
metroplex-slicerextensions_stable_nightly.cmake
metroplex.sh
overload-vs2022-slicer_500_release_package.bat
overload-vs2022-slicer_500_release_package.cmake
overload-vs2022-slicerextensions_stable_nightly.cmake
overload.bat

* Follow instructions from https://github.com/Slicer/DashboardScripts/blob/master/maintenance/guides/rename-and-update-release-scripts.md
* Remove scripts for `4.11.20210226`
* Associate 5.0.0 with directory identifier `0`
* Manually update `metroplex-slicer_500_release_package` to use
correct docker image name.
* Update overload.bat to delete `D:\D\S\S-0-E-b` instead of `D:\D\S\S-1-E-b`

Rename and update Slicer release scripts from 4.11.20210226 to 5.0.0

---

computron-slicer_preview_nightly.cmake

Exclude tests have been failing for a few months:
* **qSlicerReformatModuleWidgetGenericTest**: Issue is similar to the one associated with `qSlicerSequencesModuleWidgetGenericTest` originally excluded on `factory-south-macos` in 3d977c9259 (`factory-south-macos-slicer_500_release_package: Exclude tests expected to fail`)
* **CastScalarVolumeTest_UnsignedChar**: Issue is probably similar to the one associated with `CastScalarVolumeTest_UnsignedShort` originally excluded on `factory-south-macos` in 9bfaf7be1 (`factory-south-macos-slicer_502_release_package: Exclude tests expected to fail`)

computron: Exclude tests expected to fail

---

maintenance/guides/rename-and-update-release-scripts.md
metroplex-slicer_stable_package.sh

This ensures that the script `metroplex-slicer_stable_package.sh` references the expected build environment, guaranteeing that its execution generates the correct build environment script, now named `slicer-buildenv-qt5-centos7-slicer-5.6`.
See https://discourse.slicer.org/t/no-stable-linux-extension-packages-since-nov-26th/33150/5

Ensure version is updated in shell scripts used to generate Stable package

---

overload-vs2022-slicerextensions_preview_nightly.cmake
overload-vs2022-slicerextensions_stable_nightly.cmake

Related:
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/73

overload: Set `SlicerAutoscoperM_CUDA_PATH` to support building Autoscoper with CUDA

---

overload-vs2022-slicerextensions_preview_nightly.cmake
overload-vs2022-slicerextensions_stable_nightly.cmake

Related:
* https://github.com/Slicer/DashboardScripts/pull/63
* https://github.com/BrownBiomechanics/Autoscoper/pull/258
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/81

overload: Update SlicerAutoscoperM_CUDA_PATH from 11.8 to 12.3

---

bluestreak.bat

Follow-up of aba1c0c (`bluestreak/overload: Move SlicerPreview from "overload" to "bluestreak"`, 2024-04-29)
The commented `call` statements led to an invalid syntax. Instead, comment the complete block and explicitly call `slicerextensions_preview_nightly`

bluestreak: Fix syntax and ensure preview extension builds are triggered

---

overload-vs2022-slicer_preview_nightly.cmake
overload.bat

While the overload system cannot be reliably used for regular preview and nightly builds, we are re-enabling the build of Slicer to support local testing and development.
For more details, refer to https://discourse.slicer.org/t/windows-dashboard-extension-builds-interrupted-due-to-hardware-issue/35688
cc: @allemangD

Restore overload preview build

---

computron-slicer_preview_nightly.cmake
computron-slicerextensions_preview_nightly.cmake

This PR aims to update the CMAKE_OSX_DEPLOYMENT_TARGET for Slicer on macOS to be a version of macOS that is still supported by Apple.
This will support the following macOS versions:
- 15.x: Sequoia (2024)
- 14.x: Sonoma (2023)
- 13.x: Ventura (2022)
This is a follow-up to https://github.com/Slicer/DashboardScripts/pull/53 where the macOS deployment target was updated from 10.13 to 11.0. This PR updates the deployment target to macOS 13 (Ventura) now that macOS 15 (Sequoia) is out and Apple is no longer supporting macOS 12 (Monterey).
> [!NOTE] 
> The "computron" Slicer factory machine is running macOS 13.6.9 (Ventura) as seen in recent [build](https://slicer.cdash.org/builds/3553361).

computron: Update CMAKE_OSX_DEPLOYMENT_TARGET to 13.0

---

maintenance/metroplex/crontab
metroplex.sh

For reference, associated ctest script was the following:
```
$ cat path/to/metroplex_itk_python.cmake
cmake_minimum_required(VERSION 3.5)
set(CTEST_SITE                "metroplex.kitware")
set(CTEST_BUILD_NAME          "Linux-Python")
set(CTEST_BUILD_CONFIGURATION "Release")
set(CTEST_BUILD_FLAGS         "")
set(CTEST_CMAKE_GENERATOR     "Unix Makefiles")
set(CTEST_TEST_ARGS            PARALLEL_LEVEL 12)
set(ENV{ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS} 8)
get_filename_component(CTEST_DASHBOARD_ROOT "${CMAKE_CURRENT_LIST_DIR}/../Tests" ABSOLUTE)
set(dashboard_model Nightly)
set(dashboard_source_name ITK)
set(dashboard_binary_name ITKPython-build)
set(dashboard_cache "
ITK_WRAP_PYTHON:BOOL=ON
")
include(${CTEST_SCRIPT_DIRECTORY}/common/itk_common.cmake)
```
and corresponding shell script:
``` …
```

metroplex: Remove obsolete ITK nightly used to build ITKPython

---

metroplex-slicer_preview_nightly.cmake
metroplex-slicerextensions_preview_nightly.cmake

As of July 22nd the Linux build environment was updated where the GCC version changed from version 7 to 14. See https://discourse.slicer.org/t/slicer-build-environment-upgraded-to-qt5-almalinux8-gcc14/43802
This is to more accurately reflect the compiler that was used for the Slicer factory build when reviewing the builds over at https://slicer.cdash.org/index.php?project=SlicerPreview.

metroplex: Update compiler string to reflect updated build environment

---

bluestreak-vs2022-slicer_preview_nightly.cmake
bluestreak-vs2022-slicer_stable_package.cmake
bluestreak-vs2022-slicerextensions_preview_nightly.cmake
bluestreak-vs2022-slicerextensions_stable_nightly.cmake

This reflects the migration that took place as described at https://discourse.slicer.org/t/maintenance-of-windows-dashboard-planned-for-august-26th/44210/4

bluestreak: Update operating system string to Windows11

---

metroplex-slicersalt_stable_package.sh
metroplex.sh

This is was likely fixed in dockcross/dockcross@8f19ce7 ("Fix wrong file name in entrypoint dockcross -> dockcross.sh", 2021-08-04) itself integrated into dockbuild through dockbuild/dockbuild@9a17383 ("imagefiles 2022-01-03 (77775208)", 2022-01-03)
Related issues and pull requests:
* https://github.com/Slicer/SlicerBuildEnvironment/issues/16
* https://github.com/dockcross/dockcross/pull/536
* https://github.com/dockbuild/dockbuild/pull/78

metroplex: Remove obsolete workaround to fix image script
